album/urls.py
from django.conf.urls import patterns, url
from album import views
from django.views.generic.edit import CreateView

urlpatterns = patterns('',

        url(r'^$', views.home, name='home'),
        url(r'^album/(?P<pk>\d+)/$', views.album_view,name='album_view'),
        url(r'^image/(?P<pk>\d+)/$', views.image_view,name='image_view'),
        url(r'^upload/$', views.UploadView.as_view(), name='upload'),
        url(r'^list/', views.main, name='main'),
)

photo/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings

#from polls import views

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'tiberius.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('album.urls', namespace="album")),
    url(r'^login/$', 'django.contrib.auth.views.login'),
    url(r'^logout/$', 'django.contrib.auth.views.logout',
                                {'next_page': '/login/'})

)

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT}))

    

album/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib import admin
from django.core.files import File
from os.path import join as pjoin
from tempfile import *
import os
from PIL import Image as PImage
from django.conf import settings
from string import join
from photo.settings import MEDIA_ROOT

class Album(models.Model):
    title = models.CharField(max_length=60)
    public = models.BooleanField(default=False)
    cover = models.FileField(upload_to="images/",default=None,null=True)
    def __unicode__(self):
        return self.title

class Tag(models.Model):
    tag = models.CharField(max_length=50)
    def __unicode__(self):
        return self.tag

class Image(models.Model):
    title = models.CharField(max_length=60, blank=True, null=True)
    image = models.FileField(upload_to="images/")
    tags = models.ManyToManyField(Tag, blank=True)
    albums = models.ManyToManyField(Album, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    rating = models.IntegerField(default=50)
    width = models.IntegerField(blank=True, null=True)
    height = models.IntegerField(blank=True, null=True)
    user = models.ForeignKey(User, null=True, blank=True)

    def __unicode__(self):
        return self.image.name

    def save(self, *args, **kwargs):
        """Save image dimensions."""
        super(Image, self).save(*args, **kwargs)
        im = PImage.open(os.path.join(MEDIA_ROOT, self.image.name))
        self.width, self.height = im.size
        super(Image, self).save(*args, ** kwargs)

    def size(self):
        """Image size."""
        return "%s x %s" % (self.width, self.height)

    def __unicode__(self):
        return self.image.name

    def tags_(self):
        lst = [x[1] for x in self.tags.values_list()]
        return str(join(lst, ', '))

    def albums_(self):
        lst = [x[1] for x in self.albums.values_list()]
        return str(join(lst, ', '))

    def thumbnail(self):
        return """<a href="/media/%s"><img border="0" alt="" src="/media/%s" height="40" /></a>""" % (
                                                                    (self.image.name, self.image.name))
    thumbnail2 = models.ImageField(upload_to="images/", blank=True, null=True)

    def save(self, *args, **kwargs):
        """Save image dimensions."""
        super(Image, self).save(*args, **kwargs)
        im = PImage.open(pjoin(MEDIA_ROOT, self.image.name))
        self.width, self.height = im.size

        # large thumbnail
        fn, ext = os.path.splitext(self.image.name)
        im.thumbnail((128,128), PImage.ANTIALIAS)
        thumb_fn = fn + "-thumb2" + ext
        tf2 = NamedTemporaryFile()
        im.save(tf2.name, "JPEG")
        self.thumbnail2.save(thumb_fn, File(open(tf2.name)), save=False)
        tf2.close()


        super(Image, self).save(*args, ** kwargs)


    def get_next(self):
        next = Image.objects.filter(id__gt=self.id)
        if next:
            return next[0]
        return False


    def get_prev(self):
        prev = Image.objects.filter(id__lt=self.id).order_by('-id')
        if prev:
            return prev[0]
        return False    

album/forms.py
from django import forms
from album.models import Image
from django.contrib import admin

class UploadFileForm(forms.ModelForm):


    class Meta:
        model = Image
        fields = '__all__'
        exclude = ('user',)

album/views.py
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import get_object_or_404, render_to_response,render
from django.contrib.auth.decorators import login_required
from django.core.context_processors import csrf
from django.core.paginator import Paginator, InvalidPage, EmptyPage
from django.forms import ModelForm
from django.conf import settings
from album.models import *
from photo.settings import MEDIA_URL
from album.forms import UploadFileForm
from django.template import RequestContext
from django.views.generic.edit import CreateView
from django.contrib.auth.decorators import login_required


@login_required
def home(request):
    """Home Page."""
    if request.user.is_authenticated:
        return render(request, "album/home.html")
    else:
        return render(request, 'registration/login.html')   


@login_required
def main(request):
    """Main listing."""
    if request.user.is_authenticated:
        albums = Album.objects.all()
        if not request.user.is_authenticated():
            albums = albums.filter(public=True)

        paginator = Paginator(albums, 10)
        try: page = int(request.GET.get("page", '1'))
        except ValueError: page = 1

        try:
            albums = paginator.page(page)
        except (InvalidPage, EmptyPage):
            albums = paginator.page(paginator.num_pages)

        for album in albums.object_list:
            album.images = album.image_set.all()[:4]

        return render_to_response("album/list.html", dict(albums=albums, user=request.user,
            media_url=MEDIA_URL))
    else:
        return render(request, 'registration/login.html')

@login_required
def album_view(request, pk):
    """Album listing."""
    album = Album.objects.get(pk=pk)
    if not album.public and not request.user.is_authenticated():
        return HttpResponse("Error: you need to be logged in to view this album.")

    images = album.image_set.all()
    paginator = Paginator(images, 30)
    try: page = int(request.GET.get("page", '1'))
    except ValueError: page = 1

    try:
        images = paginator.page(page)
    except (InvalidPage, EmptyPage):
        images = paginator.page(paginator.num_pages)

    return render_to_response("album/album.html", dict(album=album, images=images, user=request.user,
        media_url=MEDIA_URL))    

@login_required
def image_view(request, pk):
    """Image page."""
    img = Image.objects.get(pk=pk)
    return render_to_response("album/image.html", dict(image=img, user=request.user,
          media_url=MEDIA_URL))


class UploadView(CreateView):
    template_name = 'album/upload.html'
    form_class = UploadFileForm


    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.user = self.request.user
        obj.save()
        return HttpResponseRedirect('/')

    def get_success_url(self):
        return reverse('album:home')

album/templates/album/album.html
{% extends "album/base.html" %}

{% block content %}
<div id="wrapper">
<ul>
    <h1>{{ album.title }}</h1>
    <ul>
        {% for img in images.object_list %}
            <a href="{% url 'album:image_view' pk=img.id %}" ><img border="0" alt=""
                src="{{ media_url }}{{ img.thumbnail2.name }}" class="album_images" /></a>
        {% endfor %}
    </ul>
</ul>
</div>
{% endblock %}

album/templates/album/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

   <title> Seaver Family Photos</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'album/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'album/css/starter-template.css' %}" rel="stylesheet">


    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>



 <div class="container-fluid">    
    <!-- Second navbar for sign in -->
    <nav class="navbar navbar-default">
      <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse-2">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'album:home' %}">The Seavers</a>
        </div>
    
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="navbar-collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="{% url 'album:home' %}">Home</a></li>
            <li><a href="{% url 'album:main' %}">Albums</a></li>

            <li><a href="mailto:shaunseaver@me.com">Contact</a></li>
            <li><a href="{% url 'django.contrib.auth.views.logout' %}">Logout ({{ user }})</a></li>


          </ul>
         
          </div>
         
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container -->
    </nav><!-- /.navbar -->
</div><!-- /.container-fluid -->







  <body>

{% block content %}


{% endblock %}


  </body>
</html>



    




</html>
    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="{% static 'album/js/jquery.min.js' %}"></script>
    <script src="{% static 'album/js/bootstrap.min.js' %}"></script>

album/templates/album/home.html
{% extends "album/base.html" %}

{% block content %}

<div id="wrapper">

<h1> Welcome </h1>
<br>
<p> I created this site as a private place for our friends and family to view/download our family photos.  In the future it may include blog entries and videos, but will be limited to photos for the time being.  If you receive any errors or encounter any bugs, please let me know. 
<br>
<h3>Enjoy the pictures!</h3>



</div>

{% endblock %}

album/templates/album/image.html
{% extends "album/base.html" %}

{% block content %}


<!-- Image -->


<div class="row row-centered">
{% if image.get_prev %}
<div class= "col-md-1" col-centered>
<a href="/image/{{ image.get_prev.id }}/" class="btn btn-info">Previous</a> 
</div>
{% endif %}
<div class= "col-md-10" col-centered>
    <ul class="image_datail">
        <img border="0" alt="" src="{{ media_url }}{{ image.image.name }}" width="900" />
    </ul>
    </div>
    {% if image.get_next %}
<div class= "col-md-1" col-centered>
<a href="/image/{{ image.get_next.id }}/" class="btn btn-info">Next</a> 
</div>
{% endif %}

</div>
<br>
<a href="{{ media_url }}{{ image.image.name }}" download class="btn btn-info" id="download_button">Download</a>




  



{% endblock %}

album/templates/album/list.html
{% extends "album/base.html" %}
{% block content %}



<div id="wrapper">
<div class="container" id="album_list">
  <div class="row">
  <div class="col-lg-12">
        <!-- Albums  -->
        <ul>
            {% for album in albums.object_list %}
                            <div class="album_title"><a href="{% url 'album:album_view' pk=album.pk %}">{{ album.title }}</a><br><img border="0" alt="" 
                            src="{{ media_url }}{{ album.cover }}" id="cover_image" /></div>

                <br>
                <br>
            {% endfor %}
        </ul>
</div>
</div>
</div>


    </div>
<br>
<br>

{% endblock %}

album/templates/album/login.html
{% if form.errors %}
<p>Your username and password didn't match. Please try again.</p>
{% endif %}


	Seaver Family Photos


<form method="post" action="{% url 'django.contrib.auth.views.login' %}">
{% csrf_token %}




<body>
     

    {{username}}
      
    {{password}}


</body>

{% block content %}
{% endblock %}


<input type="submit" class="btn btn-info" value="Submit Button">


<input type="hidden" name="next" value="{{ next }}"  />

</form>

album/templates/album/upload.html
{% extends "album/base.html" %}
{% load staticfiles %}



{% block content %}

<form action="{{ action }}" method="POST">
            {% csrf_token %}
            {{ form.as_p }}
        </form>
<input class="btn btn-default" type="submit" value="Save" />
</form>

        {% endblock %}